# Generated by Django 2.2.1 on 2021-10-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='subject',
        ),
        migrations.AddField(
            model_name='paciente',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.DateField(blank=True, null=True, verbose_name='idade'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='responsavel'),
        ),
    ]
