# Generated by Django 2.2.1 on 2021-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211018_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='phone'),
        ),
    ]
