# Generated by Django 2.2.1 on 2021-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_paciente_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone'),
        ),
    ]
