# Generated by Django 2.2.1 on 2021-11-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211101_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.CharField(max_length=255, verbose_name='um')),
                ('dois', models.CharField(max_length=255, verbose_name='dois')),
                ('tres', models.CharField(max_length=255, verbose_name='tres')),
                ('quatro', models.CharField(max_length=255, verbose_name='quatro')),
                ('cinco', models.CharField(max_length=255, verbose_name='cinco')),
                ('seis', models.CharField(max_length=255, verbose_name='seis')),
                ('sete', models.CharField(max_length=255, verbose_name='sete')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Paciente')),
            ],
        ),
    ]
