# Generated by Django 2.2.1 on 2021-11-04 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_questionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='desesseis',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='desesseis'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='desessete',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='desessete'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='dez',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='dez'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='dezenove',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='dezenove'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='dezoito',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='dezoito'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='dose',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='dose'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='nove',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='nove'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='oito',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='oito'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='onze',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='onze'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='quatorze',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='quatorze'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='quinze',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='quinze'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='treze',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='treze'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='vinte',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='vinte'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='vintedois',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='vintedois'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='vintetres',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='vintetres'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='vinteum',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='vinteum'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='cinco',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='cinco'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='dois',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='dois'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='quatro',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='quatro'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='seis',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='seis'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='sete',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='sete'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='tres',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='tres'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='um',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='um'),
        ),
    ]
