# Generated by Django 2.2.1 on 2021-11-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_paciente_dn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='desessete',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='desessete'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='dezoito',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=10, null=True, verbose_name='dezoito'),
        ),
    ]
