# Generated by Django 2.2.1 on 2022-04-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211122_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='address',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rua'),
        ),
    ]
