# Generated by Django 2.2.1 on 2022-04-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220425_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero',
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(max_length=50, null=True, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=255, null=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.DateField(null=True, verbose_name='idade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='responsavel',
            field=models.CharField(max_length=255, null=True, verbose_name='responsavel'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(max_length=255, null=True, verbose_name='rua'),
        ),
    ]
