# Generated by Django 2.2.1 on 2022-04-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20220425_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(max_length=255, null=True, verbose_name='cidade'),
        ),
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Paciente')),
            ],
        ),
    ]
