# Generated by Django 2.2.1 on 2022-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220426_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(null=True, upload_to='', verbose_name='foto'),
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
